### ISSUE TITLE
Reading headers from reqeust after authentication

### ISSUE THREAD

**Issue by pessimca** [DuendeArchive/IdentityModel.PCL#13]
Hi,

I am now to Identity model and Server and started learning for my project. We have SSO on my company side and we have to use it for authentication. Created a sample project and with hard-coded authentication (in Pre-AuthenticationSync) by creating identity principle which working fine. Now, i need to ready http headers and pull the authenticated user info and apply into identity principle. I tried to read http headers like below:

 var headers= HttpContext.Current.Request.Headers.GetValues("uid");
 if (headers!= null)
           id= headers.GetValue(0).ToString();

but it always getting empty. I tried same code on other web api project which working fine. Do we have any way to read headers on Pre-Autenthication Sync or client startup class. I appreciate your help if you can give me some thought to clear my issue.

thank you.

**Comment by leastprivilege** [comment]
Wrong repo. Use identityserver.

**Comment by pessimca** [comment]
My apologies.. Moving this question to Identity Server Repo.
