### ISSUE TITLE
Make library available to the the Xamarin.* targets

### ISSUE THREAD

**Issue by cleftheris** [DuendeArchive/IdentityModel.PCL#15]
Is it possible for the library to target the Xamarin.\* projects. As a portable library I suspect it could. Especially the enhancements over the HttpClient. 

Below is the error in visual studio when trying to add package reference from nuget.

> Could not install package 'Microsoft.Bcl.Build 1.0.14'. You are trying to install this package into a project that targets 'MonoAndroid,Version=v5.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by leastprivilege** [comment]
I don't know

**Comment by cecilphillip** [comment]
@cleftheris this seems to be related to #9

**Comment by cleftheris** [comment]
@cecilphillip  Yes, didn't see that Thanks!

**Comment by leastprivilege** [comment]
that was merged. Anything else that needs to be done?

**Comment by cleftheris** [comment]
I think this is another issue altogether. I believe it has to do with the package dependency for `Microsoft.Bcl.Build`. I just upgraded it locally to v1.0.21 and now it works.

![bcl](https://cloud.githubusercontent.com/assets/1777633/10344289/05aefaf4-6d2b-11e5-84ac-313e58cfa780.PNG)
