### ISSUE TITLE
How is this related to ThinkTecture.IdentityModel, IdentityModel45 and other earlier versions?

### ISSUE THREAD

**Issue by tofutim** [DuendeArchive/IdentityModel.PCL#2]
## I'm looking for ResourceAuthorization and wondering which repo I should be looking at.

I did some more research and found the Owin versions. However, these are linked to ThinkTecture.IdentityModel.Core. Is there a way I can use them with the pre-release nuget for IdentityModel?

**Comment by brockallen** [comment]
Resource authorization is in here: https://github.com/IdentityModel/Thinktecture.IdentityModel
