### ISSUE TITLE
What happend with ClaimsExtensions?

### ISSUE THREAD

**Issue by pawepaw** [DuendeArchive/IdentityModel.PCL#21]
In Thinktecture.IdentityModel there were claim extensions https://github.com/IdentityManager/IdentityManager/blob/master/source/Core/Extensions/ClaimsExtensions.cs. What happend with them? I can't find them in IdentityModel package.

**Comment by leastprivilege** [comment]
It's gone - these extension methods are from times were .NET did not have FindFirst/Findall and HasClaim.
