### ISSUE TITLE
TokenResult throws Invalid JSON Exception when empty string returned from client

### ISSUE THREAD

**Issue by pculver** [DuendeArchive/IdentityModel.PCL#24]
I am making a call to IdentityServer3 token revocation endpoint via TokenClient.  The raw response string coming back from identity server is the empty string.   The TokenResponse class throws an exception on construction in the JSON parser due to the empty input string.

The rough client code.

```
                    var client = new TokenClient(
            Constants.Authorization.TokenRevocationEndpoint,
            Constants.ClientDetails.Id,
            Constants.ClientDetails.Secret
            );

                    Dictionary<string, string> args = new Dictionary<string, string>()
                    { 
                         { "token", Current.Jwt }
                        ,{ "token_type_hint", "access_token" }
                    };

                    TokenResponse response = await client.RequestAsync(args);
                    response.ThrowIfError();
```

**Comment by leastprivilege** [comment]
The token client is for the token endpoint, not the revocation endpoint.

**Comment by pculver** [comment]
OK, sorry my bad.  Is there any clients for the revocation endpoint in IdentityModel?   It did seem to make the proper call into IdSvr3 according to the logs.

**Comment by leastprivilege** [comment]
No - I haven't wrapped that yet.

**Comment by pculver** [comment]
OK, I will switch to using HttpClient directly.  Thanks for your time. I appreciate it.
