### ISSUE TITLE
IntrospectionClient clientId and clientSecret refers to scope?

### ISSUE THREAD

**Issue by urbanhusky** [DuendeArchive/IdentityModel.PCL#25]
Hi,

it took me a little while to get the IntrospectionClient working because the parameters for `clientId` and `clientSecret` confused me. Shouldn't they refer to the scope instead?

**Comment by leastprivilege** [comment]
I agree that this is a bit confusing - but the middleware is a client to the introspection endpoint. ScopeName and ScopeSecret would be equally confusing together with the RequiredScopes attribute.

Changing any of those is a breaking change so we decided against it.

**Comment by urbanhusky** [comment]
True, changing that would be a breaking change. Would it make sense to provide xml documentation which mentions this for these parameters?

**Comment by leastprivilege** [comment]
What does the XML docs currently say? send a PR.

**Comment by urbanhusky** [comment]
Nothing, there is no xml documentation as far as I can tell. I can't do a PR right now, sorry.

**Comment by leastprivilege** [comment]
there are xml docs - i can improve it
