### ISSUE TITLE
Use IdentityModel inside portable projects

### ISSUE THREAD

**Issue by shackaufsaphir** [DuendeArchive/IdentityModel.PCL#27]
I try to use IdentityModel inside a portable project which is included inside a non portable project and i get the following error:

> Error CS0012 The type 'AuthorizeResponse' is defined in an assembly that is not referenced. You must add a reference to assembly 'IdentityModel.Portable, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. 
> Module C:\TFS\Sonstiges\Playground\Portable\PortableTest\Module\Module.cs 7

For a better view about my problem i created inside my GitHub project an example:
https://github.com/shackaufsaphir/playground/tree/master/SSO/IdentityModel/PortableTest

Here more details about my problem:
- I created a project **Contract** which is portable and put by NuGet the **IdentityModel.Portable** inside. 
- Inside the project **Contract** i have the following interface:

```
    public interface IFactory
    {
        void Execute(Action<AuthorizeResponse> callbackFunction);
    }
```
- Now i created the **not** portable project **Module** which has an reference to project **Contract**
- Inside **Module** i enter the following source:

```
    public class Module : IFactory
    {
        public void Execute(Action<AuthorizeResponse> callbackFunction)
        {
            throw new NotImplementedException();
        }
    }
```
- Sure I need to inside the NuGet Package of IdentityModel and Visual Studio includes the reference **IdentityModel.Net45**.
- Now i get the error (see on top of this issue).

I tried some variants but nothing works. It looks like AuthorizeResponse inside the IdentityModel.Portable and Net45 project is for Visual Studio not the same. 

To be sure i didn't made something general wrong with my portable and not portable projects i took for a try the NuGet AutoMapper inside my project and use one of there object inside my interface and that works fine. 

I do not see what i made wrong with the reference to the IdentityModel. Inside my example he shows my error direct. 
https://github.com/shackaufsaphir/playground/tree/master/SSO/IdentityModel/PortableTest

Has someone an idea what can be my problem?

I tried a little more but still don't have a solution. Has someone worked with IdentityModel in portable projects, which are used inside not portable projects? Does it general run or can it be that there is a problem inside the IdentityModel?

**Comment by JarJarBinkz** [comment]
I have the same problem. I have create a portable OpenIDConnection Manager which referenced IdentityModel Nuget-Package. The OpenIDConection Manager is used in a non-portable project and the AuthorizeResponce send from the portable project to the non-portable project.

I get the same error message:

> "Error CS0012 The type 'AuthorizeResponse' is defined in an assembly that is not referenced. You must add a reference to assembly 'IdentityModel.Portable, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. " 

The way I see it, it might be that the **signingkey** is missing and therefore the **AuthorizeResponse** object can't be passed between the portable and non- portable project.

Is there a solution for the problem already ?

**Comment by leastprivilege** [comment]
No solution. sorry. 

This seems to be a general problem with PCLs - if anybody knows how to fix it - send me a PR.

**Comment by JarJarBinkz** [comment]
Hi Dominick,

I tried a little with your project and found out, that it works when the assemblynames of the portable and non portable project are the same.

**ToDo:**
Change in both project the assemblyname to the same name (for example IdentityModel)

After your change the nuget-package must have the following result:

lib\net45\IdentityModel.dll
lib\portable-net45+wp80+win8+wpa81\IdentityModel.dll

**Comment by JarJarBinkz** [comment]
I have created a pullrequest .

[Fix IdentityModel portable reference bug](https://github.com/IdentityModel/IdentityModel/pull/31)

**Comment by brockallen** [comment]
Done and published to NuGet. Thx.
