### ISSUE TITLE
Abstracting access to IdentityServer API

### ISSUE THREAD

**Issue by mohanr** [DuendeArchive/IdentityModel.PCL#29]
I have looked at your samples. Our SPA will use OWIN to access your middleware. How do we create an abstraction layer using OWIN that hides the Identity Provider implementation ? I can switch the middleware API completely using OWIN. Is that how I do it ? When I use another identity provider I need to switch the old one with the new middleware.

**Comment by leastprivilege** [comment]
I have no clue what you are talking about - please explain.

**Comment by mohanr** [comment]
I am assuming that IdentityServer3 API will be used directly in our code.I am reading https://identityserver.github.io/Documentation/docs/overview/mvcGettingStarted.html. If we decided to use another OpenIDConnect provider then the API code is different but the protocol is the same. How do we avoid this API coupling ? 
I am just exploring OpenIDConnect and identify providers.

**Comment by leastprivilege** [comment]
That's the wrong repo btw - use the IdentityServer3 repo.

IdSrv is an openid connect implementation - so there is no "API" - it's an implementation of a standard protocol.
