### ISSUE TITLE
ClientCertificates and OAuth2Client

### ISSUE THREAD

**Issue by tofutim** [DuendeArchive/IdentityModel.PCL#3]
In a portable library (Profile111), there is no WebRequestHandler, so it is not possible to assign the Client Certificate (manual or automatic). The handler can probably be specified in platform-specific code, but I noticed that in Windows Universal apps, that support for Client Certificates comes only in the HttpClient that is Windows.Web.Http, and using an IHttpFilter.

**Comment by leastprivilege** [comment]
That's the one for store apps 

https://msdn.microsoft.com/en-us/library/system.net.http.httpclienthandler(VS.110).aspx

can't you use the same in Win10 ?

**Comment by tofutim** [comment]
I think the ClientCertificate specification can only happen in a
WebRequestHandler. There is an option to choose Automatic or Manual but no
place to specify the ClientCertificate - unless I missed something in the
spec.

**Comment by leastprivilege** [comment]
The HttpClientHandler automatically selects the cert based on SSL negotiation. Try that - I don't like the ifdef mess.

**Comment by tofutim** [comment]
I'm not sure if it does or not, but in that case the ClientCertificate
would have to be installed onto the machine and be accessible. I do see
that HttpClientHandler has an option to select the mode - Automatic or
Manual. But in the case of Manual, for a Universal App, how would you set
the ClientCertificate?

**Comment by tofutim** [comment]
It looks like I can add Client Certificates from my phone app using
https://dev.windowsphone.com/en-us/OEM/docs/Customization/Adding_certificates_to_the_phone

Is it possible to add it to the phone but still secure it with a password?

**Comment by tofutim** [comment]
This article suggests that Client Certificates are not supported in Windows
Phone 8

https://msdn.microsoft.com/library/windows/apps/ff402533#BKMK_SecureSocketsLayerSSLcertificates

But maybe 8.1 and 10 are different.

**Comment by leastprivilege** [comment]
Did you do some tests?

I also refactored the OAuth2Client - having different implementations is now easier.
