### ISSUE TITLE
User store access

### ISSUE THREAD

**Issue by mohanr** [DuendeArchive/IdentityModel.PCL#30]
The user/password store of our business is separate from the Identity server store.If this assumption is right then password encryption/decryption and checks will be based on our own logic. Then the password is converted to a claims token allowing access to our Rest API. How does the password check using our data store integrate with Identity Server ? Is this(https://identityserver.github.io/Documentation/docs/overview/mvcGettingStarted.html) how the user store should be ?

**Comment by brockallen** [comment]
Wrong repo.

**Comment by mohanr** [comment]
Which is the right repo ? I was trying to understand the procedure.
