### ISSUE TITLE
TokenClient does not return status code 400 when requesting

### ISSUE THREAD

**Issue by mclausen** [DuendeArchive/IdentityModel.PCL#32]
Hi, 

We are currently writing test agains an OpenID Connect server and we are using IdentityModel so we don't have to roll our own http client. However we ran into a litte issue when we had to test a negative case for signing in users. We recieve a 400 Bad request from Identity Server which is expected, but I am a little baffled on why you would swallow the status code in the TokenClient.

Can you help us shed some light why this design choice was made?

https://github.com/IdentityModel/IdentityModel/blob/master/source/IdentityModel.Shared/Client/TokenClient.cs#L98

**Comment by leastprivilege** [comment]
Because 200 and 400 are valid protocol responses.

**Comment by mclausen** [comment]
Sure it's valid response, but wouldn't it be optimal to have the statuscode parsed into response so you can act upon that? As of now the TokenResponse HttpStatusCode is 0, in case of a 200 or 400 responses.

**Comment by leastprivilege** [comment]
I see.  No problem just send a pr

**Comment by mclausen** [comment]
HI @leastprivilege, how come the commit was reverted?

**Comment by leastprivilege** [comment]
It broke existing clients - IsError was set to true even for valid responses.

You need to test more thoroughly - unit tests would be even better.

**Comment by mclausen** [comment]
Did you get any reports on this?

I beg to disagree. The constructor TokenResponse(HttpStatusCode statusCode, string reason) was only used in a scenario where the request had failed, and thus IsError would aways be set to true if used. However I updated the successful constructor to take in additional parameters, and defaulted the isHttpError parameter to false.

Am I wrong in this?

Do you have a collection of unittests i can submit to?

**Comment by leastprivilege** [comment]
Well - I updated the package and my code was broken. I did not have time to investigate, so I reverted.

I don't have unit tests - unfortunately. I will setup a test project ASAP.

**Comment by mclausen** [comment]
Thanks, i'll resubmit as soon its up :+1:

**Comment by leastprivilege** [comment]
check v2 - I improved the error handling there.
