### ISSUE TITLE
Not working when update IdentityModel nugget package  from version 1.3.1 to version 1.5.1.

### ISSUE THREAD

**Issue by DamirGalas** [DuendeArchive/IdentityModel.PCL#38]
I am using MVC 5, .NET 4.6.1
Not working when update IdentityModel nugget package  from version 1.3.1 to version 1.5.1.

error is:

> Could not load file or assembly 'IdentityModel.Net45, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified. 

 stack trace:

> [FileNotFoundException: Could not load file or assembly 'IdentityModel.Net45, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.]
>    IdentityServer3.AccessTokenValidation.IntrospectionEndpointTokenProvider..ctor(IdentityServerBearerTokenAuthenticationOptions options, ILoggerFactory loggerFactory) in c:\local\identity\server3\AccessTokenValidation\source\AccessTokenValidation\Plumbing\IntrospectionEndpointTokenProvider.cs:80
>    Owin.<>c__DisplayClass3.<ConfigureEndpointValidation>b__2() in c:\local\identity\server3\AccessTokenValidation\source\AccessTokenValidation\IdentityServerBearerTokenValidationAppBuilderExtensions.cs:124
>    System.Lazy`1.CreateValue() +709
>    System.Lazy`1.LazyInitValue() +191
>    Owin.IdentityServerBearerTokenValidationAppBuilderExtensions.UseIdentityServerBearerTokenAuthentication(IAppBuilder app, IdentityServerBearerTokenAuthenticationOptions options) in c:\local\identity\server3\AccessTokenValidation\source\AccessTokenValidation\IdentityServerBearerTokenValidationAppBuilderExtensions.cs:46
>    UniSrv.Server.Startup.Configuration(IAppBuilder app) in D:\Clean\uni srv 4\UniSrv\src\Server\UniSrv.Server\Startup.cs:31
> 
> [TargetInvocationException: Exception has been thrown by the target of an invocation.]
>    System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) +0
>    System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) +128
>    System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) +146
>    Owin.Loader.<>c__DisplayClass12.<MakeDelegate>b__b(IAppBuilder builder) +93
>    Owin.Loader.<>c__DisplayClass1.<LoadImplementation>b__0(IAppBuilder builder) +209
>    Microsoft.Owin.Host.SystemWeb.OwinAppContext.Initialize(Action`1 startup) +843
>    Microsoft.Owin.Host.SystemWeb.OwinBuilder.Build(Action`1 startup) +51
>    Microsoft.Owin.Host.SystemWeb.OwinHttpModule.InitializeBlueprint() +101
>    System.Threading.LazyInitializer.EnsureInitializedCore(T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory) +137
>    Microsoft.Owin.Host.SystemWeb.OwinHttpModule.Init(HttpApplication context) +172
>    System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +618
>    System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
>    System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +402
>    System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +343
> 
> [HttpException (0x80004005): Exception has been thrown by the target of an invocation.]
>    System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +579
>    System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +112
>    System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +712

**Comment by leastprivilege** [comment]
Please try to remove the nuget package - and re-install it.

**Comment by DamirGalas** [comment]
I had to uninstall also Identityserver3.AccessTokenValidation
When I install Identityserver3.AccessTokenValidation again, than I have also IdentityModel but version 1.2.1
Than is working.

But if I update to 1.5.1 than error is same.

**Comment by leastprivilege** [comment]
why do you need to update?

**Comment by leastprivilege** [comment]
I pushed an update to the access token validation MW - that should fix the inconsistency.

Does it work for you?

**Comment by DamirGalas** [comment]
Yes its work. Thank you.
