### ISSUE TITLE
TokenClient and Headers

### ISSUE THREAD

**Issue by DasNaughtie** [DuendeArchive/IdentityModel.PCL#42]
Hi Guys,

Hope all is well.

This is more of a question at this point but I've spent quite a number of hours trying to do this and just can't see how I would do this looking at the code.

I'm trying to add headers to the TokenClient so that my custom UserService can't get them from the OwinContext.Request.  I'm currently trying to implement an Integration test to do this but no joy.  Any guidance would be greatly appreciated.

**Comment by leastprivilege** [comment]
What have you tried so far?
—
cheers
Dominick Baier

**Comment by DasNaughtie** [comment]
Well, I've tried passing them into the TokenResponse as the 'extra' parameter which requires an object but that blew up.  On closer inspection it needs a dictionary of type <string, string>.  Updating to <string, string> doesn't do anything.
As for the token client...I'm using the TokenClient(ddress, clientId, clientSercet) ctor and can't see a means of adding the headers here.
Also looked at the TokenClientExtensions with a view to override the static using the new keyword but that seems like overkill and I've no guarantee it'll work.

Is there a better way?

**Comment by leastprivilege** [comment]
Use the innerhandler that you can pass into the ctor of the TokenClient. This was you have full control over the http message.

**Comment by DasNaughtie** [comment]
Cheers!  I'll give that a go.

D
