### ISSUE TITLE
Missing Extension method - UseJsonWebToken

### ISSUE THREAD

**Issue by Jenan** [DuendeArchive/IdentityModel.PCL#44]
I have tried find the extension method called "app.UseJsonWebToken".

I have tried download the packages: 
- Thinktecture.IdentityModel
- IdentityModel

But I can't find it.

Where is this extension please?

I want to implement signalr with identity server and I find the sample on the discussion where it is used:

https://github.com/IdentityServer/IdentityServer3/issues/357

```
 app.UseJsonWebToken(
            issuer: "",
            audience: "",
            signingKey: <key>,
            location: new MixedOAuthBearerAuthenticationProvider());
```

**Comment by leastprivilege** [comment]
This was just a wrapper around the standard MS JWT middleware. I don't maintain this code anymore.

**Comment by leastprivilege** [comment]
I had a quick look, but I can't find it either. sorry

**Comment by Jenan** [comment]
Thanks for good point.

I use following:

`using Microsoft.Owin.Security.Jwt;`

```
var options = new JwtBearerAuthenticationOptions
            {
                AllowedAudiences = new[] { "https://localhost:44333/core/resources" },
                IssuerSecurityTokenProviders = new[]
                {
                    new X509CertificateSecurityTokenProvider(
                        "https://localhost:44333/core",
                        Certificate.Certificate.Get())
                },
                Provider = new SignalRAuthenticationProvider()
            };

            app.UseJwtBearerAuthentication(options);
```

And work perfectly!
