### ISSUE TITLE
How do you decode an IdentityToken

### ISSUE THREAD

**Issue by joshmouch** [DuendeArchive/IdentityModel.PCL#47]
I've looked through the code all I could and I cannot find how your library is able to decode an encrypted identity token.  I have this:

```
var tokenClient = new TokenClient(tokenUri, clientId, secret);
var tokenResponse = await tokenClient.RequestAuthorizationCodeAsync(code, redirectUri);
var encryptedIdentityToken = tokenResponse.IdentityToken;
```

But I don't know what this line should look like:

```
var decryptedIdentityToken = ????
```

**Comment by brockallen** [comment]
That doesn't "decrypt" an identity token -- it's a helper to make HTTP requests to the OIDC/OAuth2 token endpoint.

**Comment by joshmouch** [comment]
Based on the Readme.cmd, I was expecting a helper method to decrypt the IdentityToken... I just couldn't find it.  But perhaps not.  I believe I can just split the response on "." and then use your Base64Url.Decode() on the three components.

**Comment by octocat-mona** [comment]
@joshmouch I think that you should look at the [JwtSecurityTokenHandler](https://msdn.microsoft.com/en-us/library/system.identitymodel.tokens.jwtsecuritytokenhandler%28v=vs.114%29.aspx) to validate and read the contents of the JWT Identity token.
You can get a JwtSecurityToken and use its Payload property.

**Comment by joshmouch** [comment]
Thanks @kpstolk .  This is exactly what I'm looking for.

**Comment by octocat-mona** [comment]
@brockallen I was just browsing through the source code and came along the `SimpleSecurityTokenHandler` class. I'm not really sure what it's supposed to do currently but couldn't (Identity) token validation be added to this library?

I've looked around and didn't find any library which does:
- Get the public key from the JWKS endpoint
- Parse and validate the token (with all the required checks on `iss`, `sub`, `aud`, `exp` etc)

**Comment by leastprivilege** [comment]
You already mentioned MS JWT handler - that's a lib you can use for that

**Comment by octocat-mona** [comment]
Still requires to handle important security issues [like this](https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/) myself, but thanks anyway :)

**Comment by leastprivilege** [comment]
No it doesn't. This library was never affected by this potential validation flaw.

**Comment by octocat-mona** [comment]
Didn't know that about this particular flaw :)
