### ISSUE TITLE
Disposing TokenClient

### ISSUE THREAD

**Issue by senj** [DuendeArchive/IdentityModel.PCL#48]
I wonder why the TokenClient does not have a dispose method as it uses the HttpClient internally?

**Comment by leastprivilege** [comment]
Oversight. feel free to send a PR

— 
cheers
Dominick Baier

On 15 July 2016 at 09:30:54, senj (notifications@github.com) wrote:

I wonder why the TokenClient does not have a dispose method as it uses the HttpClient internally?
