### ISSUE TITLE
Add support to tokenclient for using a TestServer

### ISSUE THREAD

**Issue by hvanbakel** [DuendeArchive/IdentityModel.PCL#51]
TestServer setup comes from:
https://docs.asp.net/en/latest/testing/integration-testing.html

It would be nice to use IdentityModel in unit tests to verify behavior of a mocked server. However below code fails, the server doesn't really expose the endpoint thus the test fails with a 'no response from server'

```
    [Fact]
    public async Task TestGetTokenAsync()
    {
        using (var server = new TestServer(new WebHostBuilder().UseStartup<Startup>()))
        {
            // This works (gives 400 Bad Request
            var result = server.CreateClient().GetAsync("connect/token").Result;

            // This does not
            var client = new TokenClient(server.BaseAddress + "connect/token", "client", "faultySecret");
            var result2 = await client.RequestClientCredentialsAsync("api1");
        }
    }
```

This will probably need to go into a separate package specific for unit testing.

**Comment by brockallen** [comment]
You need to pass the test server's `Handler` as the last param (of type `MessageHandler`) to the ctor of the various XxxClient classes. See here for example: https://github.com/IdentityModel/IdentityModel.Owin.PopAuthentication/blob/dev/src/IdentityModel.Owin.PopAuthentication.Tests/IntegrationTests/IdSvr_Client_And_WebApi_Integration/PopTests.cs#L122

**Comment by hvanbakel** [comment]
Ah, I hadn't found that overload yet. Thanks. 

So, for completeness, I ended up with this:

```
        using (var server = new TestServer(new WebHostBuilder().UseStartup<Startup>()))
        {
            var client = new TokenClient(
                       server.BaseAddress + "connect/token",
                       "mvc",
                       "secret",
                       server.CreateHandler());

            var result = await client.RequestClientCredentialsAsync("api1");

            Assert.NotNull(result);
            Assert.Null(result.Error);
            Assert.NotNull(result.AccessToken);
        }
```
