### ISSUE TITLE
Scope based authorization

### ISSUE THREAD

**Issue by miracles-happen** [DuendeArchive/IdentityModel.PCL#52]
Dear team,
I read a series of articles on leastprivilege.com. And I want to implement scope-based authorization in my Web Api and WCF services. 
According to article "Scope based Authorization in ASP.NET Web API" (https://leastprivilege.com/2013/06/27/scope-based-authorization-in-asp-net-web-api/) 
I should use [Scope] attribute from https://github.com/IdentityModel/Thinktecture.IdentityModel.45 repository, which is deprecated now.
And it seems, that current repository lacks the Scope attribute implementation. 
Could you please clarify, where can I get the Scope attribute?

Thanks in advance.
Best regards

**Comment by leastprivilege** [comment]
just grab the source code

**Comment by miracles-happen** [comment]
Ok, thank you for your fast response :)
Don't you plan to include it in current repo? Probably it can be confusing to have "own implementaion" (grabed from deprecated repo) and implementation in current repo (which could be implemented later)

Thank you!

**Comment by leastprivilege** [comment]
We don't to put any framework specific code anymore into identitymodel itself. Once can only maintain a limited number of code bases. 

So just take what you need and have fun ;)
