### ISSUE TITLE
refreshtoken logic is missing

### ISSUE THREAD

**Issue by mdissel** [DuendeArchive/IdentityModel.PCL#54]
Is there a reason why the refreshtoken logic is missing? (validate if accesstoken is still valid using the ExpiresIn property)

**Comment by leastprivilege** [comment]
i think you need to be a little bit more specific.

**Comment by mdissel** [comment]
Currently the TokenClient has not enough information to verify if a the accesstoken is still valid. By storing the datetime when authenticated request is executed is necessary to detect if the accesstoken is still valid and if not refresh the token (if the refres token is still valid)

**Comment by leastprivilege** [comment]
I still don't follow - why would that be a feature of the token client? It's just a protocol implementation.

**Comment by mdissel** [comment]
after some more thinking i think your are correct.
