### ISSUE TITLE
IdentityModel 2.0

### ISSUE THREAD

**Issue by DoubleExposure** [DuendeArchive/IdentityModel.PCL#55]
Does  identityModel 2.0 work with Katana or is it specific to ASP.NET Core?
Can you provide a list of assemblies that work with Katana only. I am running into issue where some of your current assemblies are ASP.NET Core only. Also, I tried to uninstall Identity Model 2.0 but Membershipreboot is dependent. So I need to know which version work with what. Thanks

**Comment by leastprivilege** [comment]
IdentityModel v2 targets plain .NET and .netstandard1.3 - not sure why this would be related to Katana?

**Comment by DoubleExposure** [comment]
Ok, well there seems to be quite a few changes to the IdentityModel 2.0 compared to the online examples.
One example: The UserInfoClient no longer takes an AccessToken but a handler object. I see no documentation on this.
