### ISSUE TITLE
AuthorizeRequest did not work with relative Uris

### ISSUE THREAD

**Issue by netsrotr** [DuendeArchive/IdentityModel.PCL#56]
If I provide a relative Uri (same origin, if IdSrv3 and Web Application are hosted within the same site) to the AuthorizeRequest ctor, the final call to .Create() cause a invalidoperationexception.

Expected: return the realtive Url inclusive query string.

**Comment by leastprivilege** [comment]
Yep - the code assumes absolute URLs. Feel free to send a PR.
