### ISSUE TITLE
IdentityModel.Extensions.HashStringExtensions not found with v2.0.0

### ISSUE THREAD

**Issue by mribichich** [DuendeArchive/IdentityModel.PCL#58]
Hi there, I have an MVC app with a WebApi. That means I'm using `UseIdentityServerBearerTokenAuthentication`and `UseCookieAuthentication` together.

For some reason when using IdentityModel 2.0.0 it was throwing `IdentityModel.Extensions.HashStringExtensions not found` and the OnValidateIdentity method was never being called.

I spent a lot of time trying multiple things, but couldn't make it work. Then I setup the logging, and saw that exception. So I installed the 1.12 version, and everything works great now.

Do you know why or need more info?

thanks!

**Comment by leastprivilege** [comment]
v2 is not compatible with v1 - hence the major version change.
