### ISSUE TITLE
IdentityModel vs Thinktecture.IdentityModel

### ISSUE THREAD

**Issue by flouk19** [DuendeArchive/IdentityModel.PCL#59]
Hi 
I am confused,
With the nuget package-manager there are two Packages available:
**Thinktecture.IdentityModel** and **IdentityModel**
what is the difference(I've seen the differences in usage) but what is the long-term difference?
Is thinktecture.IdentityModel the old version and IdentityModel the new one,
or are they not related.
Because as of security it is the best to work with the most current version,
thanks in advance
And thanks for the package you are doing a great job 👍

**Comment by leastprivilege** [comment]
Thinktecture.\* is old and deprecated.

**Comment by flouk19** [comment]
Ah okay, thanks for your quick answer, 
so I guess I have to rewrite my Id-Server :D

**Comment by leastprivilege** [comment]
yes
