### ISSUE TITLE
Using RefreshTokenHandler with HttpClient makes calling GetAsync("").Result deadlock

### ISSUE THREAD

**Issue by janobrestad** [DuendeArchive/IdentityModel.PCL#60]
Passing an instance of RefreshTokenHandler to HttpClient makes calling GetAsync synchronously by using .Result cause a deadlock. 

Example code: 
```
RefeshTokenHandler rth = new RefeshTokenHandler("https://demo.identityserver.io/connect/token", 
"clientId", "clientSecret", "refreshToken");

HttpClient client = new HttpClient(rth);
var res = client.GetAsync("https://demo.identityserver.io/api/test").Result;
```
This code will deadlock when used in a non async method in Windows Forms or WPF.

Using just the HttpClient without the RefeshTokenHandler is not deadlocking:
```
HttpClient client = new HttpClient();
client.SetBearerToken("accessToken");
var res = client.GetAsync("https://demo.identityserver.io/api/test").Result;
```

Adding ConfigureAwait(false) to the calls to base.SendAsync in the SendAsync method in RefeshTokenHandler seems to make the deadlock go away for the simple case where you don't need to refresh the token.

**Comment by leastprivilege** [comment]
OK - fixed. give it a try.
