### ISSUE TITLE
TokenClient and Headers 

### ISSUE THREAD

**Issue by mimig** [DuendeArchive/IdentityModel.PCL#69]
Hi,

I really need help with passing headers to the TokenClient. I tried using a HttpMessageHandler but could not figure out how to pass a header. Please help.

Here's a snippet of my code:

            var discovery = await _discoveryClient.GetAsync();
            
            var tokenClient = new TokenClient(discovery.TokenEndpoint, _options.TestClientId, _options.TestClientSecret);
            
            
            var tokenResponse = await tokenClient.RequestResourceOwnerPasswordAsync(
                                    userName ?? _options.DefaultUser,
                                    userPassword ?? _options.DefaultPassword,
                                    scopes ?? _options.DefaultScopes);
            return tokenResponse.AccessToken;

**Comment by leastprivilege** [comment]
The message handler is the right approach - simply add headers to the HttpRequestMessage that gets passed in.
