### ISSUE TITLE
Authorization Code Flow with OpenIdConnect Middleware

### ISSUE THREAD

**Issue by stefanodonofrio** [DuendeArchive/IdentityModel.PCL#70]
Hi All.
I'm trying to use OpenIdConnect Middleware in Owin with Authorization Code Flow. 
With the Implicit and Hybrid flow everything works fine. 
I am using IdentityModel version 1.0.0 as the Target Framework is .NET 4.5 .
There is a way to solve that?

Thank you and regards

**Comment by leastprivilege** [comment]
This is unrelated to this repo.

The OWIN middleware does not support code flow.
