### ISSUE TITLE
IntrospectionClient does not implement IDisposable

### ISSUE THREAD

**Issue by jepperc** [DuendeArchive/IdentityModel.PCL#72]
Inside it seems to be using a Httpclient, which will then not be disposed.
When used extensively inside my tests (where I am creating a lot of clients), a lot of connections are hanging around which makes the test hang, so I would like to be able to dispose of them.

Is there a reason for not implementing IDisposable or should I contribute with a PR?

**Comment by leastprivilege** [comment]
It's fixed in 3.0 - currently pre-release on nuget - will publish the final one soon.

**Comment by leastprivilege** [comment]
https://www.nuget.org/packages/IdentityModel/3.0.0-ardbeg
