### ISSUE TITLE
Please sign the assembly

### ISSUE THREAD

**Issue by huer12** [DuendeArchive/IdentityModel.PCL#8]
The assembly is not signed, because of that I can't add it as nuget package, I had to copy the source files. 
Our project requires signed assemblies.

**Comment by brockallen** [comment]
You mean strong name or authenticode signature? Search our archives -- this has been discussed before and we have no plan to strong name our assemblies.

**Comment by huer12** [comment]
Yes, strong name is what i mean. Thanks for the quick answer. 
Here the link to the discussion: https://github.com/IdentityModel/Thinktecture.IdentityModel.45/issues/50
I see your point, I guess I have to start the discussion in our project team about strong names. I also don't see a reason why this has been done in our project, but this has been done 8 years ago...
