### ISSUE TITLE
Add support for Profile78 or Profile259

### ISSUE THREAD

**Issue by akamud** [DuendeArchive/IdentityModel.PCL#9]
Can IdentityModel be used on [Profile78](http://fastchicken.co.nz/2014/02/24/further-adventures-in-pcl-profile78-and-json-net/) or [Profile259](http://danrigby.com/2014/04/16/xamarin-pcl-profile-notes/)? I'm trying to use this on Xamarin, but from what I saw, it targets Profile111, which is not compatible with PCL projects that is used in both Xamarin.Android and Xamarin.iOS

I see [Thinktecture.IdentityModel.Client](https://www.nuget.org/packages/Thinktecture.IdentityModel.Client/) supports Profile259, which is compatible with the case mentioned above.

**Comment by leastprivilege** [comment]
PR?

**Comment by akamud** [comment]
Doing that right now :)

**Comment by akamud** [comment]
Any feedback on this?

**Comment by leastprivilege** [comment]
I am back from holidays now and will start working again next week - will have a look then. thanks!

**Comment by akamud** [comment]
Oops, sorry about interrupting your days off :grin:
